version: '3.8'
services:
  db:
    image: mysql:8.3
    container_name: meu_mysql
    environment:
      MYSQL_DATABASE: nome_do_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      MYSQL_ROOT_PASSWORD: senha_root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
